/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AuthSessionExpiredRouteImport } from './routes/auth.session-expired'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'
import { Route as AdminReferralsRouteImport } from './routes/admin.referrals'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminReferralsIndexRouteImport } from './routes/admin.referrals.index'
import { Route as AdminCmsIndexRouteImport } from './routes/admin.cms.index'
import { Route as AdminReferralsLeaderboardRouteImport } from './routes/admin.referrals.leaderboard'
import { Route as AdminReferralsAnalyticsRouteImport } from './routes/admin.referrals.analytics'
import { Route as AdminReferralsIdRouteImport } from './routes/admin.referrals.$id'
import { Route as AdminCmsTestimonialsRouteImport } from './routes/admin.cms.testimonials'
import { Route as AdminCmsStatisticsRouteImport } from './routes/admin.cms.statistics'
import { Route as AdminCmsSocialRouteImport } from './routes/admin.cms.social'
import { Route as AdminCmsSeoRouteImport } from './routes/admin.cms.seo'
import { Route as AdminCmsNavigationRouteImport } from './routes/admin.cms.navigation'
import { Route as AdminCmsFooterRouteImport } from './routes/admin.cms.footer'
import { Route as AdminCmsFeaturesRouteImport } from './routes/admin.cms.features'
import { Route as AdminCmsFaqsRouteImport } from './routes/admin.cms.faqs'
import { Route as AdminCmsAnnouncementRouteImport } from './routes/admin.cms.announcement'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSessionExpiredRoute = AuthSessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralsIndexRoute = AdminReferralsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminReferralsRoute,
} as any)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminReferralsLeaderboardRoute =
  AdminReferralsLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AdminReferralsRoute,
  } as any)
const AdminReferralsAnalyticsRoute = AdminReferralsAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminReferralsRoute,
} as any)
const AdminReferralsIdRoute = AdminReferralsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminReferralsRoute,
} as any)
const AdminCmsTestimonialsRoute = AdminCmsTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsStatisticsRoute = AdminCmsStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsSocialRoute = AdminCmsSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsSeoRoute = AdminCmsSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsNavigationRoute = AdminCmsNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsFooterRoute = AdminCmsFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsFeaturesRoute = AdminCmsFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsFaqsRoute = AdminCmsFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsAnnouncementRoute = AdminCmsAnnouncementRouteImport.update({
  id: '/announcement',
  path: '/announcement',
  getParentRoute: () => AdminCmsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/referrals': typeof AdminReferralsRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cms/announcement': typeof AdminCmsAnnouncementRoute
  '/admin/cms/faqs': typeof AdminCmsFaqsRoute
  '/admin/cms/features': typeof AdminCmsFeaturesRoute
  '/admin/cms/footer': typeof AdminCmsFooterRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/seo': typeof AdminCmsSeoRoute
  '/admin/cms/social': typeof AdminCmsSocialRoute
  '/admin/cms/statistics': typeof AdminCmsStatisticsRoute
  '/admin/cms/testimonials': typeof AdminCmsTestimonialsRoute
  '/admin/referrals/$id': typeof AdminReferralsIdRoute
  '/admin/referrals/analytics': typeof AdminReferralsAnalyticsRoute
  '/admin/referrals/leaderboard': typeof AdminReferralsLeaderboardRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/referrals/': typeof AdminReferralsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cms/announcement': typeof AdminCmsAnnouncementRoute
  '/admin/cms/faqs': typeof AdminCmsFaqsRoute
  '/admin/cms/features': typeof AdminCmsFeaturesRoute
  '/admin/cms/footer': typeof AdminCmsFooterRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/seo': typeof AdminCmsSeoRoute
  '/admin/cms/social': typeof AdminCmsSocialRoute
  '/admin/cms/statistics': typeof AdminCmsStatisticsRoute
  '/admin/cms/testimonials': typeof AdminCmsTestimonialsRoute
  '/admin/referrals/$id': typeof AdminReferralsIdRoute
  '/admin/referrals/analytics': typeof AdminReferralsAnalyticsRoute
  '/admin/referrals/leaderboard': typeof AdminReferralsLeaderboardRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/admin/referrals': typeof AdminReferralsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/admin/referrals': typeof AdminReferralsRouteWithChildren
  '/admin/waitlist': typeof AdminWaitlistRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/session-expired': typeof AuthSessionExpiredRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cms/announcement': typeof AdminCmsAnnouncementRoute
  '/admin/cms/faqs': typeof AdminCmsFaqsRoute
  '/admin/cms/features': typeof AdminCmsFeaturesRoute
  '/admin/cms/footer': typeof AdminCmsFooterRoute
  '/admin/cms/navigation': typeof AdminCmsNavigationRoute
  '/admin/cms/seo': typeof AdminCmsSeoRoute
  '/admin/cms/social': typeof AdminCmsSocialRoute
  '/admin/cms/statistics': typeof AdminCmsStatisticsRoute
  '/admin/cms/testimonials': typeof AdminCmsTestimonialsRoute
  '/admin/referrals/$id': typeof AdminReferralsIdRoute
  '/admin/referrals/analytics': typeof AdminReferralsAnalyticsRoute
  '/admin/referrals/leaderboard': typeof AdminReferralsLeaderboardRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/admin/referrals/': typeof AdminReferralsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/cms'
    | '/admin/referrals'
    | '/admin/waitlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/session-expired'
    | '/admin/'
    | '/admin/cms/announcement'
    | '/admin/cms/faqs'
    | '/admin/cms/features'
    | '/admin/cms/footer'
    | '/admin/cms/navigation'
    | '/admin/cms/seo'
    | '/admin/cms/social'
    | '/admin/cms/statistics'
    | '/admin/cms/testimonials'
    | '/admin/referrals/$id'
    | '/admin/referrals/analytics'
    | '/admin/referrals/leaderboard'
    | '/admin/cms/'
    | '/admin/referrals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/waitlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/session-expired'
    | '/admin'
    | '/admin/cms/announcement'
    | '/admin/cms/faqs'
    | '/admin/cms/features'
    | '/admin/cms/footer'
    | '/admin/cms/navigation'
    | '/admin/cms/seo'
    | '/admin/cms/social'
    | '/admin/cms/statistics'
    | '/admin/cms/testimonials'
    | '/admin/referrals/$id'
    | '/admin/referrals/analytics'
    | '/admin/referrals/leaderboard'
    | '/admin/cms'
    | '/admin/referrals'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/cms'
    | '/admin/referrals'
    | '/admin/waitlist'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/session-expired'
    | '/admin/'
    | '/admin/cms/announcement'
    | '/admin/cms/faqs'
    | '/admin/cms/features'
    | '/admin/cms/footer'
    | '/admin/cms/navigation'
    | '/admin/cms/seo'
    | '/admin/cms/social'
    | '/admin/cms/statistics'
    | '/admin/cms/testimonials'
    | '/admin/referrals/$id'
    | '/admin/referrals/analytics'
    | '/admin/referrals/leaderboard'
    | '/admin/cms/'
    | '/admin/referrals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/session-expired': {
      id: '/auth/session-expired'
      path: '/session-expired'
      fullPath: '/auth/session-expired'
      preLoaderRoute: typeof AuthSessionExpiredRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals': {
      id: '/admin/referrals'
      path: '/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referrals/': {
      id: '/admin/referrals/'
      path: '/'
      fullPath: '/admin/referrals/'
      preLoaderRoute: typeof AdminReferralsIndexRouteImport
      parentRoute: typeof AdminReferralsRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/referrals/leaderboard': {
      id: '/admin/referrals/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/referrals/leaderboard'
      preLoaderRoute: typeof AdminReferralsLeaderboardRouteImport
      parentRoute: typeof AdminReferralsRoute
    }
    '/admin/referrals/analytics': {
      id: '/admin/referrals/analytics'
      path: '/analytics'
      fullPath: '/admin/referrals/analytics'
      preLoaderRoute: typeof AdminReferralsAnalyticsRouteImport
      parentRoute: typeof AdminReferralsRoute
    }
    '/admin/referrals/$id': {
      id: '/admin/referrals/$id'
      path: '/$id'
      fullPath: '/admin/referrals/$id'
      preLoaderRoute: typeof AdminReferralsIdRouteImport
      parentRoute: typeof AdminReferralsRoute
    }
    '/admin/cms/testimonials': {
      id: '/admin/cms/testimonials'
      path: '/testimonials'
      fullPath: '/admin/cms/testimonials'
      preLoaderRoute: typeof AdminCmsTestimonialsRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/statistics': {
      id: '/admin/cms/statistics'
      path: '/statistics'
      fullPath: '/admin/cms/statistics'
      preLoaderRoute: typeof AdminCmsStatisticsRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/social': {
      id: '/admin/cms/social'
      path: '/social'
      fullPath: '/admin/cms/social'
      preLoaderRoute: typeof AdminCmsSocialRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/seo': {
      id: '/admin/cms/seo'
      path: '/seo'
      fullPath: '/admin/cms/seo'
      preLoaderRoute: typeof AdminCmsSeoRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/navigation': {
      id: '/admin/cms/navigation'
      path: '/navigation'
      fullPath: '/admin/cms/navigation'
      preLoaderRoute: typeof AdminCmsNavigationRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/footer': {
      id: '/admin/cms/footer'
      path: '/footer'
      fullPath: '/admin/cms/footer'
      preLoaderRoute: typeof AdminCmsFooterRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/features': {
      id: '/admin/cms/features'
      path: '/features'
      fullPath: '/admin/cms/features'
      preLoaderRoute: typeof AdminCmsFeaturesRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/faqs': {
      id: '/admin/cms/faqs'
      path: '/faqs'
      fullPath: '/admin/cms/faqs'
      preLoaderRoute: typeof AdminCmsFaqsRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/announcement': {
      id: '/admin/cms/announcement'
      path: '/announcement'
      fullPath: '/admin/cms/announcement'
      preLoaderRoute: typeof AdminCmsAnnouncementRouteImport
      parentRoute: typeof AdminCmsRoute
    }
  }
}

interface AdminCmsRouteChildren {
  AdminCmsAnnouncementRoute: typeof AdminCmsAnnouncementRoute
  AdminCmsFaqsRoute: typeof AdminCmsFaqsRoute
  AdminCmsFeaturesRoute: typeof AdminCmsFeaturesRoute
  AdminCmsFooterRoute: typeof AdminCmsFooterRoute
  AdminCmsNavigationRoute: typeof AdminCmsNavigationRoute
  AdminCmsSeoRoute: typeof AdminCmsSeoRoute
  AdminCmsSocialRoute: typeof AdminCmsSocialRoute
  AdminCmsStatisticsRoute: typeof AdminCmsStatisticsRoute
  AdminCmsTestimonialsRoute: typeof AdminCmsTestimonialsRoute
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
}

const AdminCmsRouteChildren: AdminCmsRouteChildren = {
  AdminCmsAnnouncementRoute: AdminCmsAnnouncementRoute,
  AdminCmsFaqsRoute: AdminCmsFaqsRoute,
  AdminCmsFeaturesRoute: AdminCmsFeaturesRoute,
  AdminCmsFooterRoute: AdminCmsFooterRoute,
  AdminCmsNavigationRoute: AdminCmsNavigationRoute,
  AdminCmsSeoRoute: AdminCmsSeoRoute,
  AdminCmsSocialRoute: AdminCmsSocialRoute,
  AdminCmsStatisticsRoute: AdminCmsStatisticsRoute,
  AdminCmsTestimonialsRoute: AdminCmsTestimonialsRoute,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
}

const AdminCmsRouteWithChildren = AdminCmsRoute._addFileChildren(
  AdminCmsRouteChildren,
)

interface AdminReferralsRouteChildren {
  AdminReferralsIdRoute: typeof AdminReferralsIdRoute
  AdminReferralsAnalyticsRoute: typeof AdminReferralsAnalyticsRoute
  AdminReferralsLeaderboardRoute: typeof AdminReferralsLeaderboardRoute
  AdminReferralsIndexRoute: typeof AdminReferralsIndexRoute
}

const AdminReferralsRouteChildren: AdminReferralsRouteChildren = {
  AdminReferralsIdRoute: AdminReferralsIdRoute,
  AdminReferralsAnalyticsRoute: AdminReferralsAnalyticsRoute,
  AdminReferralsLeaderboardRoute: AdminReferralsLeaderboardRoute,
  AdminReferralsIndexRoute: AdminReferralsIndexRoute,
}

const AdminReferralsRouteWithChildren = AdminReferralsRoute._addFileChildren(
  AdminReferralsRouteChildren,
)

interface AdminRouteChildren {
  AdminCmsRoute: typeof AdminCmsRouteWithChildren
  AdminReferralsRoute: typeof AdminReferralsRouteWithChildren
  AdminWaitlistRoute: typeof AdminWaitlistRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCmsRoute: AdminCmsRouteWithChildren,
  AdminReferralsRoute: AdminReferralsRouteWithChildren,
  AdminWaitlistRoute: AdminWaitlistRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSessionExpiredRoute: typeof AuthSessionExpiredRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSessionExpiredRoute: AuthSessionExpiredRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
